name: Build and test

on:
  pull_request:

jobs:
  build-test:
    if: github.repository == 'akka/akka-http-quickstart-scala.g8'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.3

      - name: sbt & Paradox
        run: sbt test docs/paradox

